CREATE TABLE [dbo].[CitizenComments]
(
	[Id] INT IDENTITY(1,1) NOT NULL PRIMARY KEY, 
    [Name] NVARCHAR(50) NOT NULL, 
    [Email] NVARCHAR(50) NOT NULL, 
    [City] NVARCHAR(50) NOT NULL, 
    [Address] NVARCHAR(50) NOT NULL, 
    [Comment] NVARCHAR(250) NOT NULL, 
    [Date] DATETIME NOT NULL
)
